# Machine learnning comprehensive notebook
## Notebook has all tricks

### All python imports

In [45]:
# 📚 Essential Libraries
import numpy as np
import pandas as pd

# 📊 Visualization Libraries
import matplotlib.pyplot as plt
import seaborn as sns

# 🔍 Statistical Libraries
from scipy.stats import norm, skew
from scipy import stats

# ⚠️ Ignore warnings
import warnings
warnings.filterwarnings('ignore')

# 🎨 Set visualization style
sns.set(style="whitegrid")

from lightgbm import early_stopping, log_evaluation
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import HistGradientBoostingRegressor
from sklearn.impute import SimpleImputer
from sklearn.metrics import root_mean_squared_error
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold, train_test_split
import ydf as tfdf # tensorflow decision forests
from sklearn.pipeline import make_pipeline
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from xgboost import XGBClassifier
from xgboost import XGBRegressor
import lightgbm as lgb
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf



print("✅ Libraries Imported Successfully!")

✅ Libraries Imported Successfully!

In [46]:
# Set options to prevent line breaks and expand display
pd.set_option('display.max_columns', None) # Show all columns
pd.set_option('display.width', None)      # Set a large display width
pd.set_option('display.max_colwidth', None)  # Show full content of cells (unlimited width)
pd.set_option('display.expand_frame_repr', False) # Prevent wrapping the frame representation

In [47]:
# 📥 Load datasets
train = pd.read_csv("/Users/vkdvamshi/gitRepos/ai-ml-learnings/titanicspaceship/train.csv" , header=0 )
test = pd.read_csv("/Users/vkdvamshi/gitRepos/ai-ml-learnings/titanicspaceship/test.csv" , header=0 )

# 🔍 Initial exploration
print("✅ Data Loaded Successfully!")

✅ Data Loaded Successfully!

In [48]:
# 🔢 Shape of datasets
print(f"📌 Training Data Shape: {train.shape}")
print(f"📌 Test Data Shape: {test.shape}")
print ( f"📌Training Info: {train.info()}" )
print ( f"📌Test Info: {test.info()}" )

📌 Training Data Shape: (8693, 14)
📌 Test Data Shape: (4277, 13)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8693 entries, 0 to 8692
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PassengerId   8693 non-null   object
 1   HomePlanet    8492 non-null   object
 2   CryoSleep     8476 non-null   object
 3   Cabin         8494 non-null   object
 4   Destination   8511 non-null   object
 5   Age           8514 non-null   float64
 6   VIP           8490 non-null   object
 7   RoomService   8512 non-null   float64
 8   FoodCourt     8510 non-null   float64
 9   ShoppingMall  8485 non-null   float64
 10  Spa           8510 non-null   float64
 11  VRDeck        8505 non-null   float64
 12  Name          8493 non-null   object
 13  Transported   8693 non-null   bool
dtypes: bool(1), float64(6), object(7)
memory usage: 891.5+ KB
📌Training Info: None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4277 entries, 0 to 4276
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PassengerId   4277 non-null   object
 1   HomePlanet    4190 non-null   object
 2   CryoSleep     4184 non-null   object
 3   Cabin         4177 non-null   object
 4   Destination   4185 non-null   object
 5   Age           4186 non-null   float64
 6   VIP           4184 non-null   object
 7   RoomService   4195 non-null   float64
 8   FoodCourt     4171 non-null   float64
 9   ShoppingMall  4179 non-null   float64
 10  Spa           4176 non-null   float64
 11  VRDeck        4197 non-null   float64
 12  Name          4183 non-null   object
dtypes: float64(6), object(7)
memory usage: 434.5+ KB
📌Test Info: None

In [49]:




print ( """describe() method gives you the statistical summary of the dataset. 
It includes measures such as count, mean, standard deviation, minimum, 25th percentile, median (50th percentile), 75th percentile, and maximum 
for each numerical column in the dataset. 
This information helps you understand the distribution and central tendency of the data, as well as identify any potential outliers or anomalies.

count gives you all the non-null values in the dataset. if the count is not the same for all columns then it means there are some null values in the dataset.
mean gives you the average value of the column.

Quick Data Overview: It helps you get intimate with your data quickly, providing an initial overview before deeper analysis.
Data Distribution: By looking at the mean, median (50%), min, max, and standard deviation, you can get a sense of how the data is distributed and identify potential skewness or outliers.
Spotting Data Issues: It can help check for missing values (by comparing count to the total expected entries) or unusual values.
Categorical Insights: For non-numeric data, it reveals the most common categories and the variety of entries, which is useful for understanding categorical distributions. 

Here’s what each part means:
count: Number of non-null (non-missing) entries. In this case, 5 for both columns.
mean: The average value. For Age, it’s 35. For Salary, it’s 77,000.
std (Standard Deviation): Tells you how spread out the data is. A high value means more variability.
min: The smallest value in the column.
25%, 50%, 75% (Percentiles/Quartiles):
25%: The first quartile — 25% of the data falls below this value.
50%: The median (middle value).
75%: The third quartile — 75% of the data falls below this value.
max: The highest value in the column.
.1 (10%) and .9 (90%) help you understand the distribution of extreme values.

""")
print ( f"📌Training Describe:\n {train.describe()}" )
print ( f"📌Test Describe:\n {test.describe()}" )

# 🔎 First look at training data
print("\n🔹 First 5 rows of Training Data:")
display(train.head())

# 🔎 First look at test data
print("\n🔹 First 5 rows of Test Data:")
display(test.head())

# Check sample values of labels

describe() method gives you the statistical summary of the dataset.
It includes measures such as count, mean, standard deviation, minimum, 25th percentile, median (50th percentile), 75th percentile, and maximum
for each numerical column in the dataset.
This information helps you understand the distribution and central tendency of the data, as well as identify any potential outliers or anomalies.

count gives you all the non-null values in the dataset. if the count is not the same for all columns then it means there are some null values in the dataset.
mean gives you the average value of the column.

Quick Data Overview: It helps you get intimate with your data quickly, providing an initial overview before deeper analysis.
Data Distribution: By looking at the mean, median (50%), min, max, and standard deviation, you can get a sense of how the data is distributed and identify potential skewness or outliers.
Spotting Data Issues: It can help check for missing values (by comparing count to the total expected entries) or unusual values.
Categorical Insights: For non-numeric data, it reveals the most common categories and the variety of entries, which is useful for understanding categorical distributions.

Here’s what each part means:
count: Number of non-null (non-missing) entries. In this case, 5 for both columns.
mean: The average value. For Age, it’s 35. For Salary, it’s 77,000.
std (Standard Deviation): Tells you how spread out the data is. A high value means more variability.
min: The smallest value in the column.
25%, 50%, 75% (Percentiles/Quartiles):
25%: The first quartile — 25% of the data falls below this value.
50%: The median (middle value).
75%: The third quartile — 75% of the data falls below this value.
max: The highest value in the column.
.1 (10%) and .9 (90%) help you understand the distribution of extreme values.


📌Training Describe:
                Age   RoomService     FoodCourt  ShoppingMall           Spa        VRDeck
count  8514.000000   8512.000000   8510.000000   8485.000000   8510.000000   8505.000000
mean     28.827930    224.687617    458.077203    173.729169    311.138778    304.854791
std      14.489021    666.717663   1611.489240    604.696458   1136.705535   1145.717189
min       0.000000      0.000000      0.000000      0.000000      0.000000      0.000000
25%      19.000000      0.000000      0.000000      0.000000      0.000000      0.000000
50%      27.000000      0.000000      0.000000      0.000000      0.000000      0.000000
75%      38.000000     47.000000     76.000000     27.000000     59.000000     46.000000
max      79.000000  14327.000000  29813.000000  23492.000000  22408.000000  24133.000000
📌Test Describe:
                Age   RoomService     FoodCourt  ShoppingMall           Spa        VRDeck
count  4186.000000   4195.000000   4171.000000   4179.000000   4176.000000   4197.000000
mean     28.658146    219.266269    439.484296    177.295525    303.052443    310.710031
std      14.179072    607.011289   1527.663045    560.821123   1117.186015   1246.994742
min       0.000000      0.000000      0.000000      0.000000      0.000000      0.000000
25%      19.000000      0.000000      0.000000      0.000000      0.000000      0.000000
50%      26.000000      0.000000      0.000000      0.000000      0.000000      0.000000
75%      37.000000     53.000000     78.000000     33.000000     50.000000     36.000000
max      79.000000  11567.000000  25273.000000   8292.000000  19844.000000  22272.000000

🔹 First 5 rows of Training Data:

  PassengerId HomePlanet CryoSleep  Cabin  Destination   Age    VIP  RoomService  FoodCourt  ShoppingMall     Spa  VRDeck               Name  Transported
0     0001_01     Europa     False  B/0/P  TRAPPIST-1e  39.0  False          0.0        0.0           0.0     0.0     0.0    Maham Ofracculy        False
1     0002_01      Earth     False  F/0/S  TRAPPIST-1e  24.0  False        109.0        9.0          25.0   549.0    44.0       Juanna Vines         True
2     0003_01     Europa     False  A/0/S  TRAPPIST-1e  58.0   True         43.0     3576.0           0.0  6715.0    49.0      Altark Susent        False
3     0003_02     Europa     False  A/0/S  TRAPPIST-1e  33.0  False          0.0     1283.0         371.0  3329.0   193.0       Solam Susent        False
4     0004_01      Earth     False  F/1/S  TRAPPIST-1e  16.0  False        303.0       70.0         151.0   565.0     2.0  Willy Santantines         True

🔹 First 5 rows of Test Data:

  PassengerId HomePlanet CryoSleep  Cabin  Destination   Age    VIP  RoomService  FoodCourt  ShoppingMall     Spa  VRDeck              Name
0     0013_01      Earth      True  G/3/S  TRAPPIST-1e  27.0  False          0.0        0.0           0.0     0.0     0.0   Nelly Carsoning
1     0018_01      Earth     False  F/4/S  TRAPPIST-1e  19.0  False          0.0        9.0           0.0  2823.0     0.0    Lerome Peckers
2     0019_01     Europa      True  C/0/S  55 Cancri e  31.0  False          0.0        0.0           0.0     0.0     0.0   Sabih Unhearfus
3     0021_01     Europa     False  C/1/S  TRAPPIST-1e  38.0  False          0.0     6652.0           0.0   181.0   585.0  Meratz Caltilter
4     0023_01      Earth     False  F/5/S  TRAPPIST-1e  20.0  False         10.0        0.0         635.0     0.0     0.0   Brence Harperez

### a. Drop the columns that are not useful for modeling
### b. Remove id value which are sequenctial and do not add any value to the model
### c. Remove name as it is unique for each passenger and does not add any value to the model
### d. Convert True / False to 1/0 for better modeling
### e. Convert categorical variables to numerical using one-hot encoding or label encoding as needed
### f. Handle missing values by imputing with mean/median for numerical features and mode for categorical features, or by using more advanced imputation techniques if necessary.
### g. Feature engineering: Create new features that might be useful for the model, such as family size (SibSp + Parch), or extract titles from names if they were not dropped.
### h. Scale numerical features if needed, especially for algorithms that are sensitive to feature scaling (e.g., SVM, KNN).
### i. Encode the target variable (if it's categorical) into numerical format for modeling.
### j. Ensure that the same preprocessing steps are applied to both the training and test datasets to maintain consistency.
### k. After preprocessing, split the training data into features (X) and target variable (y) for model training.
### l. Perform exploratory data analysis (EDA) to understand the relationships between features and the target variable, and to identify any potential issues in the data.
### m. split the columns if necessary which has multiple values

In [50]:
train.head()

  PassengerId HomePlanet CryoSleep  Cabin  Destination   Age    VIP  RoomService  FoodCourt  ShoppingMall     Spa  VRDeck               Name  Transported
0     0001_01     Europa     False  B/0/P  TRAPPIST-1e  39.0  False          0.0        0.0           0.0     0.0     0.0    Maham Ofracculy        False
1     0002_01      Earth     False  F/0/S  TRAPPIST-1e  24.0  False        109.0        9.0          25.0   549.0    44.0       Juanna Vines         True
2     0003_01     Europa     False  A/0/S  TRAPPIST-1e  58.0   True         43.0     3576.0           0.0  6715.0    49.0      Altark Susent        False
3     0003_02     Europa     False  A/0/S  TRAPPIST-1e  33.0  False          0.0     1283.0         371.0  3329.0   193.0       Solam Susent        False
4     0004_01      Earth     False  F/1/S  TRAPPIST-1e  16.0  False        303.0       70.0         151.0   565.0     2.0  Willy Santantines         True

In [51]:


train.drop(columns=['PassengerId', 'Name'], inplace=True)
train[["Deck", "Cabin_num", "Side"]] = train["Cabin"].str.split("/", expand=True)

## Onehot encoding for categorical variables
ordinal_encoder = OrdinalEncoder()
s = (train.dtypes == 'object')
object_cols = list(s[s].index)
train[object_cols] = ordinal_encoder.fit_transform(train[object_cols])

# check the missing values in the dataset 
train.isnull().sum().sort_values(ascending=False)
train.head()

   HomePlanet  CryoSleep   Cabin  Destination   Age  VIP  RoomService  FoodCourt  ShoppingMall     Spa  VRDeck  Transported  Deck  Cabin_num  Side
0         1.0        0.0   149.0          2.0  39.0  0.0          0.0        0.0           0.0     0.0     0.0        False   1.0        0.0   0.0
1         0.0        0.0  2184.0          2.0  24.0  0.0        109.0        9.0          25.0   549.0    44.0         True   5.0        0.0   1.0
2         1.0        0.0     1.0          2.0  58.0  1.0         43.0     3576.0           0.0  6715.0    49.0        False   0.0        0.0   1.0
3         1.0        0.0     1.0          2.0  33.0  0.0          0.0     1283.0         371.0  3329.0   193.0        False   0.0        0.0   1.0
4         0.0        0.0  2186.0          2.0  16.0  0.0        303.0       70.0         151.0   565.0     2.0         True   5.0        1.0   1.0

In [52]:
X = train.drop(columns=['Transported'])
y = train['Transported']

In [53]:
X.head()

   HomePlanet  CryoSleep   Cabin  Destination   Age  VIP  RoomService  FoodCourt  ShoppingMall     Spa  VRDeck  Deck  Cabin_num  Side
0         1.0        0.0   149.0          2.0  39.0  0.0          0.0        0.0           0.0     0.0     0.0   1.0        0.0   0.0
1         0.0        0.0  2184.0          2.0  24.0  0.0        109.0        9.0          25.0   549.0    44.0   5.0        0.0   1.0
2         1.0        0.0     1.0          2.0  58.0  1.0         43.0     3576.0           0.0  6715.0    49.0   0.0        0.0   1.0
3         1.0        0.0     1.0          2.0  33.0  0.0          0.0     1283.0         371.0  3329.0   193.0   0.0        0.0   1.0
4         0.0        0.0  2186.0          2.0  16.0  0.0        303.0       70.0         151.0   565.0     2.0   5.0        1.0   1.0

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
imputer = SimpleImputer(strategy='mean')
X_train_imputed = imputer.fit_transform(X_train)
X_test_imputed = imputer.transform(X_test)

model = HistGradientBoostingRegressor()
model.fit(X_train, y_train)

predictions = model.predict(X_test)

mae = mean_absolute_error(y_test, predictions)
mse = mean_squared_error(y_test, predictions)
r2 = r2_score(y_test, predictions)

print(f'Mean Absolute Error: {mae}')
print(f'Mean Squared Error: {mse}')

Mean Absolute Error: 0.2655711664347296
Mean Squared Error: 0.13497468581426655
R-squared: 0.460049656410375